### Import Packages

In [1]:
import json
import requests
import pandas as pd
import numpy as np
import datetime

pd.options.mode.chained_assignment = None  # default='warn'
np.set_printoptions(suppress=True)
pd.set_option('display.float_format', '{:.2f}'.format)

### Import historical data

In [4]:
import requests
import pandas as pd

response = requests.get("https://api.covid19india.org/v4/min/timeseries.min.json")
if response.status_code == 200:
    historical_day_numbers = response.json()
    DATE = []
    STATE = []
    TOTAL_CASES = []
    RECOVERED = []
    DECEASED = []
    TESTED = []
    VACCINATED_DOSE1 = []
    VACCINATED_DOSE2 = []
    
       
    for state in historical_day_numbers.keys():
        for date in historical_day_numbers[state]['dates'].keys():
            STATE.append(state)
            DATE.append(date)
            #Using try and except since in some dates cases calues are not available. So, except adds a zero where cases are not
            #available
            try:
                TOTAL_CASES.append(historical_day_numbers[state]['dates'][date]['delta']['confirmed'])
            except:
                TOTAL_CASES.append(0)
            try:
                RECOVERED.append(historical_day_numbers[state]['dates'][date]['delta']['recovered'])
            except:
                RECOVERED.append(0)
            try:
                DECEASED.append(historical_day_numbers[state]['dates'][date]['delta']['deceased'])
            except:
                DECEASED.append(0)
            try:
                TESTED.append(historical_day_numbers[state]['dates'][date]['delta']['tested'])
            except:
                TESTED.append(0)
            try:
                VACCINATED_DOSE1.append(historical_day_numbers[state]['dates'][date]['delta']['vaccinated1'])
            except:
                VACCINATED_DOSE1.append(0)
            try:
                VACCINATED_DOSE2.append(historical_day_numbers[state]['dates'][date]['delta']['vaccinated2'])
            except:
                VACCINATED_DOSE2.append(0)

            
    Covid19_historical_data = pd.DataFrame(
        {
            
            "STATE/UT": STATE,
            "DATE": DATE,
            "TOTAL_CASES": TOTAL_CASES,
            "RECOVERED": RECOVERED,
            "DECEASED": DECEASED,
            "TESTED": TESTED,
            "VACCINATED_DOSE1": VACCINATED_DOSE1,
            "VACCINATED_DOSE2": VACCINATED_DOSE2,
       }
    )
    #print(data.head())

else:
    print("Error while calling API: {}".format(response.status_code, response.reason))

In [5]:
#Changing DATE column format
Covid19_historical_data['DATE']= pd.to_datetime(Covid19_historical_data['DATE'], format = '%Y-%m-%d')

In [13]:
#Check sample data
Covid19_historical_data.head()

,STATE/UT,DATE,TOTAL_CASES,RECOVERED,DECEASED,TESTED,VACCINATED_DOSE1,VACCINATED_DOSE2
0,AN,2020-03-26,1,0,0,0,0,0
1,AN,2020-03-27,5,0,0,0,0,0
2,AN,2020-03-28,3,0,0,0,0,0
3,AN,2020-03-29,0,0,0,0,0,0
4,AN,2020-03-30,1,0,0,0,0,0

In [8]:
#Changing DATE column format
Covid19_historical_data['DATE']= pd.to_datetime(Covid19_historical_data['DATE'], format = '%Y-%m-%d')

### Import 7 DAY moving average data

In [9]:
import requests
import pandas as pd

response = requests.get("https://api.covid19india.org/v4/min/timeseries.min.json")
if response.status_code == 200:
    historical_day_numbers = response.json()
    DATE = []
    STATE = []
    TOTAL_CASES = []
    RECOVERED = []
    DECEASED = []
    TESTED = []
    VACCINATED_DOSE1 = []
    VACCINATED_DOSE2 = []
    
       
    for state in historical_day_numbers.keys():
        for date in historical_day_numbers[state]['dates'].keys():
            STATE.append(state)
            DATE.append(date)
            #Using try and except since in some dates cases calues are not available. So, except adds a zero where cases are not
            #available
            try:
                TOTAL_CASES.append(historical_day_numbers[state]['dates'][date]['delta7']['confirmed'])
            except:
                TOTAL_CASES.append(0)
            try:
                RECOVERED.append(historical_day_numbers[state]['dates'][date]['delta7']['recovered'])
            except:
                RECOVERED.append(0)
            try:
                DECEASED.append(historical_day_numbers[state]['dates'][date]['delta7']['deceased'])
            except:
                DECEASED.append(0)
            try:
                TESTED.append(historical_day_numbers[state]['dates'][date]['delta7']['tested'])
            except:
                TESTED.append(0)
            try:
                VACCINATED_DOSE1.append(historical_day_numbers[state]['dates'][date]['delta7']['vaccinated1'])
            except:
                VACCINATED_DOSE1.append(0)
            try:
                VACCINATED_DOSE2.append(historical_day_numbers[state]['dates'][date]['delta7']['vaccinated2'])
            except:
                VACCINATED_DOSE2.append(0)

            
    Covid19_7DMA_data = pd.DataFrame(
        {
            
            "STATE/UT": STATE,
            "DATE": DATE,
            "TOTAL_CASES": TOTAL_CASES,
            "RECOVERED": RECOVERED,
            "DECEASED": DECEASED,
            "TESTED": TESTED,
            "VACCINATED_DOSE1": VACCINATED_DOSE1,
            "VACCINATED_DOSE2": VACCINATED_DOSE2,
       }
    )
    #print(data.head())

else:
    print("Error while calling API: {}".format(response.status_code, response.reason))

In [10]:
#Changing DATE column format
Covid19_7DMA_data['DATE']= pd.to_datetime(Covid19_7DMA_data['DATE'], format = '%Y-%m-%d')

In [14]:
#Check sample data
Covid19_7DMA_data.tail()

,STATE/UT,DATE,TOTAL_CASES,RECOVERED,DECEASED,TESTED,VACCINATED_DOSE1,VACCINATED_DOSE2
18491,WB,2021-08-02,4999,5686,76,296421,1696928,486544
18492,WB,2021-08-03,5066,5604,75,296840,1862738,484482
18493,WB,2021-08-04,5077,5631,71,304199,1926066,447844
18494,WB,2021-08-05,5123,5632,70,307132,2104970,446486
18495,WB,2021-08-06,5129,5584,74,311696,2206769,417030